#数据库相关配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movies
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

#swagger相关配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '在线电影用户端'
      paths-to-match: '/**'
      packages-to-scan: com.movies.controller
